[package]
name = "tmc-langs-node"
version = "0.1.0"
authors = ["University of Helsinki <mooc@cs.helsinki.fi>", "Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"
license = "MIT OR Apache-2.0"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies.neon]
version = "0.8"
default-features = false
features = ["napi-6"]

[dependencies]
tmc-langs = { path = "../../tmc-langs", features = ["ts"] }

base64 = "0.13"
env_logger = "0.8"
serde = "1"
serde_json = "1"
thiserror = "1"
ts-rs = { git = "https://github.com/Heliozoa/ts-rs/", branch = "ext" }
