[package]
name = "tmc-server-mock"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde_json = "1.0.78"
mockito = "1.0.2"
