[package]
name = "tmc-server-mock"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde_json = "1.0.78"
mockito = "0.31.0"
