[workspace]
members = [
    # core libraries
    "tmc-client",
    "tmc-langs",
    "tmc-langs-cli",
    "tmc-langs-framework",
    "tmc-langs-plugins",
    "tmc-langs-util",

    # language plugins
    "plugins/csharp",
    "plugins/java",
    "plugins/make",
    "plugins/notests",
    "plugins/python3",
    "plugins/r",

    # bindings to other languages
    "bindings/tmc-langs-node",

    # test helpers
    "tmc-server-mock",
]
resolver = "2"

[workspace.package]
authors = [
    "University of Helsinki <mooc@cs.helsinki.fi>",
    "Daniel Martinez <daniel.x.martinez@helsinki.fi>",
]
edition = "2021"
rust-version = "1.58.1"
license = "MIT OR Apache-2.0"
