[workspace]
members = [
    # core libraries
    "crates/tmc-*",

    # language plugins
    "crates/plugins/*",

    # bindings to other languages
    "crates/bindings/*",

    # test helpers
    "crates/helpers/*",
]
resolver = "2"

[workspace.package]
authors = [
    "University of Helsinki <mooc@cs.helsinki.fi>",
    "Daniel Martinez <daniel.x.martinez@helsinki.fi>",
]
edition = "2021"
rust-version = "1.58.1"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
tmc-client = { path = "crates/tmc-client" }
tmc-langs = { path = "crates/tmc-langs" }
tmc-langs-framework = { path = "crates/tmc-langs-framework" }
tmc-langs-plugins = { path = "crates/tmc-langs-plugins" }
tmc-langs-util = { path = "crates/tmc-langs-util" }
tmc-langs-csharp = { path = "crates/plugins/csharp" }
tmc-langs-java = { path = "crates/plugins/java" }
tmc-langs-make = { path = "crates/plugins/make" }
tmc-langs-notests = { path = "crates/plugins/notests" }
tmc-langs-python3 = { path = "crates/plugins/python3" }
tmc-langs-r = { path = "crates/plugins/r" }
tmc-server-mock = { path = "crates/helpers/tmc-server-mock" }
