[workspace]
members = [
    # core libraries
    "tmc-client",
    "tmc-langs",
    "tmc-langs-cli",
    "tmc-langs-framework",
    "tmc-langs-plugins",
    "tmc-langs-util",

    # language plugins
    "plugins/csharp",
    "plugins/java",
    "plugins/make",
    "plugins/notests",
    "plugins/python3",
    "plugins/r",

    # bindings to other languages
    "bindings/tmc-langs-node",

    # test helpers
    "tmc-server-mock",
]
resolver = "2"
