[package]
name = "tmc-langs-node"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Bindings to the tmc-langs library for Node"
license.workspace = true
rust-version.workspace = true
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies.neon]
version = "0.10.0"
default-features = false
features = ["napi-6", "default-panic-hook"]

[dependencies]
tmc-langs = { workspace = true, features = ["ts"] }

base64 = "0.13.0"
env_logger = "0.9.0"
serde = "1.0.136"
serde_json = "1.0.78"
thiserror = "1.0.30"
ts-rs = { git = "https://github.com/Heliozoa/ts-rs/", features = [
    "serde-compat",
], rev = "f78e0c43b62266a49a227e20733aca6467970f13" }

[dev-dependencies]
log = "0.4.14"
once_cell = "1.9.0"
simple_logger = "2.1.0"
tmc-server-mock .workspace = true
