name: Run tests

on:
  push:
    branches: [master, "[0-9]+.[0-9]+"]
  pull_request:
    branches: [master, "[0-9]+.[0-9]+"]

env:
  RUST_LOG: debug,j4rs=warn
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-C debuginfo=0"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Diagnostics on Windows
        if: matrix.os == 'windows-latest'
        run: "gci env:"

      - name: Rustfmt
        run: cargo fmt -- --check
      - name: Clippy
        if: matrix.os == 'ubuntu-latest'
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Build test binary
        run: cargo test --no-run

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update -y
          sudo apt install -y check valgrind  # required for make plugin
          sudo apt install -y libcurl4-gnutls-dev libgit2-dev # required for R

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install C#
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Install R
        if: matrix.os == 'ubuntu-latest'
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: "3.5.3"
      - name: Install tmc-r-tester
        if: matrix.os == 'ubuntu-latest'
        run: |
          Rscript -e 'install.packages(c("testthat", "jsonlite", "R.utils"))'
          Rscript -e 'install.packages("plugins/r/tests/tmcRtestrunner", repos=NULL, type="source")'

      - name: Run tests
        run: cargo test --no-fail-fast
