name: Run tests

on:
  push:
    branches: [master, "[0-9]+.[0-9]+"]
  pull_request:
    branches: [master, "[0-9]+.[0-9]+"]

env:
  RUST_LOG: debug,j4rs=warn

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install depedencies
        run: |
          sudo apt update -y
          sudo apt install -y check valgrind  # required for make plugin
          sudo apt install -y libcurl4-gnutls-dev libgit2-dev # required for R
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: "3.5.3"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Install tmc-r-tester
        run: |
          Rscript -e 'install.packages(c("testthat", "jsonlite", "R.utils"))'
          Rscript -e 'install.packages("plugins/r/tests/tmcRtestrunner", repos=NULL, type="source")'
      - name: Build test binary
        run: cargo test --no-run --verbose
      - name: Run tests
        run: |
          cargo test --verbose --no-fail-fast
          npm --prefix ./bindings/tmc-langs-node run jest

  windows:
    runs-on: windows-latest
    steps: # TODO: install missing dependencies and run all tests on windows
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Diagnostics
        run: "gci env:"
      - name: Build test binary
        run: cargo test --no-run --verbose
      - name: Run tests
        run: |
          cargo test --verbose --no-fail-fast
          npm --prefix ./bindings/tmc-langs-node run jest

  macos:
    runs-on: macos-latest
    steps: # TODO: install missing dependencies and run all tests on macos
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Build test binary
        run: cargo test --no-run --verbose
      - name: Run tests
        run: |
          cargo test --verbose --no-fail-fast
          npm --prefix ./bindings/tmc-langs-node run jest
