[package]
name = "tmc-langs"
version = "0.26.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tmc-client.workspace = true
tmc-langs-plugins.workspace = true
tmc-langs-framework.workspace = true
tmc-langs-util.workspace = true

base64 = "0.13.0"
dirs = "4.0.0"
# heim = { version = "0.1.0-beta.3", features = ["disk"] }
hmac = { version = "0.12.0", features = ["std"] }
impl-enum = "0.3.0"
jwt = "0.16.0"
log = "0.4.14"
md5 = "0.7.0"
oauth2 = { version = "4.0.0-beta.1", features = ["reqwest"] }
once_cell = "1.9.0"
regex = "1.5.4"
rpassword = "7.0.0"
schemars = "0.8.8"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
serde_yaml = "0.9.10"
sha2 = "0.10.1"
shellwords = "1.1.0"
smol = "1.2.5"
tar = "0.4.38"
tempfile = "3.3.0"
thiserror = "1.0.30"
toml = "0.5.8"
ts-rs = { git = "https://github.com/Heliozoa/ts-rs.git", rev = "d1eeeabc857b824f3cdaec97270c33d3cf0eda35", features = [
    "serde-compat",
    "toml-impl",
], optional = true }
url = "2.2.2"
walkdir = "2.3.2"
zip = "0.6.3"
zstd = "0.11.2"

[target.'cfg(unix)'.dependencies]
nix = "0.25.0"

[dev-dependencies]
chrono = "0.4.19"
mockito = "0.31.0"
simple_logger = "4.0.0"
tempfile = "3.3.0"

[features]
ts-rs = [
    "dep:ts-rs",
    "tmc-client/ts-rs",
    "tmc-langs-framework/ts-rs",
    "tmc-langs-util/ts-rs",
]
